### ISSUE TITLE
ERROR: No module named 'termios'

### ISSUE THREAD

**Issue by lengocthuong15** [ceccopierangiolieugenio/tlogg#1]
Hi, I can install tlogg through pip, but when I run it, an error has occurred 
`ERROR: No module named 'termios'`

I use Windows 10

**Comment by ceccopierangiolieugenio** [comment]
Hi, Unfortunately I have not adapted the [pyTermTk](https://github.com/ceccopierangiolieugenio/pyTermTk) library to be used with windows (i have no windows machine I can test it).
but maybe I can use temporarely ncurses to achieve the same result.
In the meantime you can try to use WSL or Cygwin under windows.

**Comment by lengocthuong15** [comment]
Thank you, I am using WSL to overcome this.
