### ISSUE TITLE
Great tool! a Couple of questions

### ISSUE THREAD

**Issue by castben** [ceccopierangiolieugenio/tlogg#2]
Hi I was looking at this project, and it is really nice. 

I was wondering to see if I can adap some of your techniques to my own log-viewer tool (this one is specialized to transform logs from a format to another), for example logs coming from kibana, somtimes they came like CSV, or JSON format; my program take those and re-format them to a chosen format so they are easy to read.

I was using TextEdit widget for this purpose, but have find out loading large files is not very good to do it, so a better approach is required.

I was seeing your tlogg tool and it is great how it manage huge files, and if I understand what your program is doing is loading file per chunks and it load(and drops) "pages" as they are required.

So few questions I have around this:

I see you use TTkFileBuffer, I right to think this method will load required pages  from file and return an array containing corresponding lines that are specified by that page?

Also, I looks widget you used  to show log lines is a list? or at least looks like a list...?  only option I did not saw on your tool is wrap line. so that is why I think is a kind of list...

I will experiment with this TTkFileBuffer, as I was building a similar approach but it doesn't make sense if you did already!...

**Comment by ceccopierangiolieugenio** [comment]
**TTkFileBuffer** Is a very old helper class I made to read-only and show very big files.
It provide a simple interface to retrieve any line and automatically buffer the results to minimise the access to the disk and avoid loading the entire file in the memory.
I based its buffering mechanism to the way the linux kernel load the virtual memory pages.

The wrap feature implemented in the text editor is a very tricky and time consuming routine, anytime you resize the widget the wrap index is regenerated and if you have a big file opened, it may take way too much time to be usable.
I was thinking about implementing some king of Fast-Wrapping routine.
Still haven't thought about all the implications because this is going to affect the index of the scrollbar since there are more lines to be displayed and I don't know what it is going to happen if the wrapping happen dynamically only in the area displayed.

In your case I would implement a visual wrap (i.e. how it happen in vim), you get the lines you are suppose to display and wrap them automatically in the canvas (losing the bottom ones), this is definitely the fastest way a wrap may be achieved (and probably I should add the option in the editor as well), the only draw-back (as it happen in vim) is that if the line is so long that the wrapping goes below the last line displayed (not very common but it happen), there is no way to see the end of the wrapped line.

The **tlogg** viewer widget is a custom one, it is not based on the editor and It is designed to be as simple as possible.
Instead of adapting the editor that didn't exists when I first coded tlogg and it is not optimised for large files, I preferred to write a custom widget in order to have a better control over it.

I can help you to write a custom similar widget (with fast wrap included)

Anyway, how big is your file?
Once you convert it, you keep it in the memory? (in this case I wouldn't use the FileBuffer since it is already in the memory)
Are you thinking instead of using the Buffering mechanism to load the file in chunks and convert it dynamically? (i think it is doable)

Do you have some examples of your CSV,Json files and the results expected?

**Comment by castben** [comment]
Hi thank you for your advices, yes I did realised this was a custom widget you created (I found line where you put together all line with line number and coloring, vey clever!).

Yes of course I can give an example of a single line and how it looks like (this is only 1 line of log):

```
{"@timestamp":"2023-07-24T14:39:15.474Z","level":"ERROR","message":"Exception during node registration: Certificate signing request has been rejected: Rejection reason code: 11.\n Description: Other.\n Additional remark: null.","processId":"162","threadId":"main","traceId":"","spanId":"","logger":"net.corda.node.internal.NodeStartupLogging","stacktrace":" net.corda.node.utilities.registration.CertificateRequestException: Certificate signing request has been rejected: Rejection reason code: 11.\n Description: Other.\n Additional remark: null.\n\tat net.corda.node.utilities.registration.HTTPNetworkRegistrationService.retrieveCertificates(HTTPNetworkRegistrationService.kt:64)\n\tat net.corda.node.utilities.registration.NetworkRegistrationHelper.pollServerForCertificates(NetworkRegistrationHelper.kt:353)\n\tat net.corda.node.utilities.registration.NetworkRegistrationHelper.generateKeyPairAndCertificate(NetworkRegistrationHelper.kt:164)\n\tat net.corda.node.utilities.registration.NetworkRegistrationHelper.generateNodeCA(NetworkRegistrationHelper.kt:138)\n\tat net.corda.node.utilities.registration.NodeRegistrationHelper.generateKeysAndRegister(NetworkRegistrationHelper.kt:552)\n\tat net.corda.node.utilities.registration.NetworkRegistrationHelper.generateKeysAndRegister$default(NetworkRegistrationHelper.kt:114)\n\tat net.corda.node.internal.subcommands.InitialRegistration.registerWithNetwork(InitialRegistrationCli.kt:113)\n\tat net.corda.node.internal.subcommands.InitialRegistration.access$registerWithNetwork(InitialRegistrationCli.kt:70)\n\tat net.corda.node.internal.subcommands.InitialRegistration$initialRegistration$1.invoke(InitialRegistrationCli.kt:132)\n\tat net.corda.node.internal.subcommands.InitialRegistration$initialRegistration$1.invoke(InitialRegistrationCli.kt:70)\n\tat net.corda.node.internal.NodeStartupLogging$DefaultImpls.attempt(NodeStartup.kt:572)\n\tat net.corda.node.internal.subcommands.InitialRegistration.attempt(InitialRegistrationCli.kt:70)\n\tat net.corda.node.internal.subcommands.InitialRegistration.initialRegistration(InitialRegistrationCli.kt:132)\n\tat net.corda.node.internal.subcommands.InitialRegistration.run(InitialRegistrationCli.kt:154)\n\tat net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:219)\n\tat net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:154)\n\tat net.corda.node.internal.NodeStartupLogging$DefaultImpls.attempt(NodeStartup.kt:572)\n\tat net.corda.node.internal.NodeStartup.attempt(NodeStartup.kt:154)\n\tat net.corda.node.internal.NodeStartup.initialiseAndRun(NodeStartup.kt:218)\n\tat net.corda.node.internal.NodeStartup.initialiseAndRun$default(NodeStartup.kt:166)\n\tat net.corda.node.internal.subcommands.InitialRegistrationCli.runProgram(InitialRegistrationCli.kt:45)\n\tat net.corda.node.internal.NodeStartupCli.runProgram(NodeStartup.kt:128)\n\tat net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:201)\n\tat net.corda.node.internal.NodeStartupCli.call(NodeStartup.kt:99)\n\tat net.corda.node.internal.NodeStartupCli.call(NodeStartup.kt:72)\n\tat picocli.CommandLine.execute(CommandLine.java:1173)\n\tat picocli.CommandLine.access$800(CommandLine.java:141)\n\tat picocli.CommandLine$RunLast.handle(CommandLine.java:1367)\n\tat picocli.CommandLine$RunLast.handle(CommandLine.java:1335)\n\tat picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)\n\tat picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)\n\tat net.corda.cliutils.CordaCliWrapperKt.start(CordaCliWrapper.kt:90)\n\tat net.corda.node.Corda.main(Corda.kt:13)\n","tenantId": "","additional_fields":"[]"}
```

So you can imagine reading a file with hundred of thousand of lines like this to try to trace an issue...
in this case if you pay attention this is actually a json format, so every single line is like this (of coruse it differs on info each line has, but format is same)

my program scan file  (and expecting all of them have same formatting) it extract all fields found on json format:
![image](https://github.com/ceccopierangiolieugenio/tlogg/assets/56597585/d0ec992e-7508-46cd-b4b0-fe6cecedbaf5)

Then you select fields you actually want to see:
![image](https://github.com/ceccopierangiolieugenio/tlogg/assets/56597585/85829fb3-c2da-4ef4-ab67-b381ae2007da)

And apply it to file and you get something like this:

Then I simply create a temp file and reload result that looks like this, if user likes it then it can be exported(with a new name to conserve original one):
```
2023-07-24T14:39:15.474Z ERROR Exception during node registration: Certificate signing request has been rejected: Rejection reason code: 11.
 Description: Other.
 Additional remark: null.  net.corda.node.utilities.registration.CertificateRequestException: Certificate signing request has been rejected: Rejection reason code: 11.
 Description: Other.
 Additional remark: null.
	at net.corda.node.utilities.registration.HTTPNetworkRegistrationService.retrieveCertificates(HTTPNetworkRegistrationService.kt:64)
	at net.corda.node.utilities.registration.NetworkRegistrationHelper.pollServerForCertificates(NetworkRegistrationHelper.kt:353)
	at net.corda.node.utilities.registration.NetworkRegistrationHelper.generateKeyPairAndCertificate(NetworkRegistrationHelper.kt:164)
	at net.corda.node.utilities.registration.NetworkRegistrationHelper.generateNodeCA(NetworkRegistrationHelper.kt:138)
	at net.corda.node.utilities.registration.NodeRegistrationHelper.generateKeysAndRegister(NetworkRegistrationHelper.kt:552)
	at net.corda.node.utilities.registration.NetworkRegistrationHelper.generateKeysAndRegister$default(NetworkRegistrationHelper.kt:114)
	at net.corda.node.internal.subcommands.InitialRegistration.registerWithNetwork(InitialRegistrationCli.kt:113)
	at net.corda.node.internal.subcommands.InitialRegistration.access$registerWithNetwork(InitialRegistrationCli.kt:70)
	at net.corda.node.internal.subcommands.InitialRegistration$initialRegistration$1.invoke(InitialRegistrationCli.kt:132)
	at net.corda.node.internal.subcommands.InitialRegistration$initialRegistration$1.invoke(InitialRegistrationCli.kt:70)
	at net.corda.node.internal.NodeStartupLogging$DefaultImpls.attempt(NodeStartup.kt:572)
	at net.corda.node.internal.subcommands.InitialRegistration.attempt(InitialRegistrationCli.kt:70)
	at net.corda.node.internal.subcommands.InitialRegistration.initialRegistration(InitialRegistrationCli.kt:132)
	at net.corda.node.internal.subcommands.InitialRegistration.run(InitialRegistrationCli.kt:154)
	at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:219)
	at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:154)
	at net.corda.node.internal.NodeStartupLogging$DefaultImpls.attempt(NodeStartup.kt:572)
	at net.corda.node.internal.NodeStartup.attempt(NodeStartup.kt:154)
	at net.corda.node.internal.NodeStartup.initialiseAndRun(NodeStartup.kt:218)
	at net.corda.node.internal.NodeStartup.initialiseAndRun$default(NodeStartup.kt:166)
	at net.corda.node.internal.subcommands.InitialRegistrationCli.runProgram(InitialRegistrationCli.kt:45)
	at net.corda.node.internal.NodeStartupCli.runProgram(NodeStartup.kt:128)
	at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:201)
	at net.corda.node.internal.NodeStartupCli.call(NodeStartup.kt:99)
	at net.corda.node.internal.NodeStartupCli.call(NodeStartup.kt:72)
	at picocli.CommandLine.execute(CommandLine.java:1173)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at net.corda.cliutils.CordaCliWrapperKt.start(CordaCliWrapper.kt:90)
	at net.corda.node.Corda.main(Corda.kt:13)
```
I'm still working with CSV format but is the same principle.

My program was doing all this on line of command, but then I added an `interactive mode` which is what you see on screenshot to make it even easier to work with.

People I shown this interface they love it and remind them time of NightCommand and other old text based UI's.

some files may have millions of  lines.  The preformatting as I envisoned initially is like a `preview` of what you will get exporting file. I'm trying to manage small files, I've tested medium files around 50MB and they load well on textEdit and work well too, but as you said wordwrap is slow when it is applied to these files.

I've tested fileBuffer api and it is cool I like it. I think will work to what I'm thinking to do.

**Comment by ceccopierangiolieugenio** [comment]
I think the log viewer widget can be easily adapted to display this kind of data
Unfortunately I don't have much time in those days but I'd like to try a prototype
Is this the typical log4j format?

**Comment by castben** [comment]
Well this output is "custom" produced; 
There're few tools on market to manage logs; these tools concentrate all logs from several sources(mainly from kubernete clusters) into a single place to allow support engineers and devs to check logs in a centralized way.

Some of these tools are for example elasticsearch, kibana, datatdog etc.

In my particular case sceneario each customer can manage their logs as they wish, when we ask for logs to fix a particular issue, they sent to us an "export" view of what they had on these centralized systems ( using for example Kibana), they select what fields to add on this file, and which format export file will have (json, csv, custom), for us as support engineers sometimes these logs are massive, and to add more difficulty, they send it in a specific format (like json, csv, etc).

So I was tired to see this kind of files (even though we ask customers to send to us  as "plain log text" sometimes they do not had this option). So we sometimes struggle to trace an issues with these massive files with an akward format to see.

That is main purpose of my program. So far it is running well at the command line, it reads file and show it in a "easy to read" format;  I've just  added an "interactive" option to give more flexibility.

Also customer can change the actual "raw log format" to whatever format they want using log4j but this is other case (for example putting severity level in front of each line followed by the timestamp, and then rest...) these file are still  readable but not as hard as  the one with json or csv formats.

Do not worry. I will ask you for help if I need. So far fileBuffer API is working as I wish for my purpose.
